from sqlalchemy import Column, Integer, String, Float, Date, Text
from sqlalchemy.sql import func
from app.db.database import Base

class HRData(Base):
    __tablename__ = "hr_data"

    id = Column(Integer, primary_key=True, index=True)
    month = Column(String, index=True)
    date = Column(Date, index=True)
    month_year = Column(String, index=True)
    year = Column(Integer, index=True)
    count = Column(Integer)
    emp_id = Column(String, index=True)
    employee_name = Column(String, index=True)
    date_of_birth = Column(Date)
    age = Column(Integer)
    gender = Column(String, index=True)
    date_of_joining = Column(Date)
    band = Column(String, index=True)
    designation = Column(String, index=True)
    process = Column(String, index=True)
    voice_non_voice = Column(String)
    account_name = Column(String, index=True)
    domain = Column(String, index=True)
    department = Column(String, index=True)
    manager = Column(String, index=True)
    functional_head = Column(String)
    location = Column(String, index=True)
    sub_location = Column(String)
    country = Column(String, index=True)
    date_of_resignation = Column(Date)
    last_working_day = Column(Date)
    date_of_intimation_of_attrition = Column(Date)
    reason = Column(Text)
    voluntary_involuntary = Column(String, index=True)
    nascom_attrition_analysis = Column(String)
    new_country = Column(String)
    active_count = Column(Integer)
    new_hire = Column(Integer)
    opening_hc = Column(Integer)
    overall_inactive_count = Column(Integer)
    inactive_count = Column(Integer)
    age_group = Column(String, index=True)
    tenure_bucket = Column(String, index=True)
